openapi: 3.0.3
info:
  title: CEP API
  description: |-
    This API was made to calculate the shipping for each region of Brazil.
  contact:
    email: emanuelcavalcanteb@gmail.com
  version: 1.0.0
servers:
  - url: https://cep-api.swagger.io/v1
tags:
  - name: cep
    description: Consult your zip code
paths:
  /consulta-endereco:
    post:
      tags:
        - cep
      summary: Consult your zip code to get the shipping price.
      description: Consult your zip code.
      operationId: verifyCEP
      requestBody:
        description: Verify a CEP.
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/CEPWithoutMask'
                - $ref: '#/components/schemas/CEPWithMask'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CEPResponseSuccessful'
        '400':
          description: CEP was not found.
components:
  schemas:
    CEPWithoutMask:
      required:
        - cep
      type: object
      properties:
        cep:
          type: string
          example: 01001000
          minLength: 8
          maxLength: 8
          pattern: /^\d{5}-?\d{3}$/gm
    CEPWithMask:
      required:
        - cep
      type: object
      properties:
        cep:
          type: string
          example: 01001-000
          minLength: 9
          maxLength: 9
          pattern: /^\d{5}-?\d{3}$/gm
    CEPResponseSuccessful:
      type: object
      properties:
        cep:
          type: string
          example: 01001-000
        rua:
          type: string
          example: Praça da Sé
        complemento:
          type: string
          example: lado ímpar
        bairro:
          type: string
          example: Sé
        cidade:
          type: string
          example: São Paulo
        estado:
          type: string
          example: SP
        frete:
          type: number
          example: 7.85
